### ISSUE TITLE
sqlwhat-ext readthedocs build failing

### ISSUE THREAD

**Issue by rv2e** [datacamp/sqlwhat-ext#4]
@machow commented on [Thu Dec 28 2017](https://github.com/datacamp/learn-bugs/issues/133)

http://sqlwhat-ext.readthedocs.io/en/latest/#

**Comment by rv2e** [comment]
It seems to be up again

**Comment by machow** [comment]
It produced an empty page with no documentation

![image](https://user-images.githubusercontent.com/2574498/36821706-55e1b248-1cc2-11e8-985c-d720feed8b9b.png)

**Comment by filipsch** [comment]
Duplicate of #3

**Comment by filipsch** [comment]
Fixed in https://github.com/datacamp/sqlwhat-ext/commit/60cfb72cbd9ee8e42c6cdfd71aff246c99a8357a

See http://sqlwhat-ext.readthedocs.io/en/latest/
